server:
  port: 8081
  error:
    path: /error
jwt:
  secret: 'supersecret'
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dhaulagiri?createDatabaseIfNotExist=true
    password: root
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        
